### PR TITLE
Integrate with wikidata

### LINKED ISSUE #16: Allow the prompt-creator to specify output templates
Similarly to how Listeria does this, it should be possible for the caller of the template to specify local templates that get called for the header(s) and each "row" returned, so as to have full control over the output themselves.

### LINKED ISSUE #18: Not having to copy and paste
Currently the output of the script needs to be copied by hand into the Wikidata page. Make it so that the script can add this text itself.

### PR DESCRIPTION
**Pull request by chrismytton**
This uses the [mediawiki-page-replaceable_content](https://github.com/everypolitician/mediawiki-page-replaceable_content) library to interact with Wikidata directly.

Fixes #18 

## Notes to merger

Please complete the following before merging:

- [x] Change base branch to `master` once #28 has been merged.

### CODE REVIEW

**Comment by lucychambers** [comment]
Hey @chrismytton 

I obviously can't read the code on this but I'm just checking on the basis that the comment is written as it implies that there are multiple things combined in this PR. Do we need both of them to be combined here - or is combining them preventing one which is actually finished from being released?

**Comment by chrismytton** [comment]
> I obviously can't read the code on this but I'm just checking on the basis that the comment is written as it implies that there are multiple things combined in this PR. Do we need both of them to be combined here - or is combining them preventing one which is actually finished from being released?

Yes, I think integrating with mediawiki-page-replaceable_content can go through now, and the templates can go through in a separate pull request. I've updated this pull request so it's only doing one thing and updated the original description to reflect this.

**Comment by chrismytton** [comment]
I've moved the custom template bits into https://github.com/everypolitician/compare_with_wikidata/pull/27 ➡️

**Comment by lucychambers** [comment]
Thank you!

**Comment by chrismytton** [comment]
I've also split out moving the mediawiki text generation to a template ➡️ https://github.com/everypolitician/compare_with_wikidata/pull/28

**Comment by chrismytton** [comment]
This pull request will need to be rebase onto `master` once #28 has been merged.

**Comment by chrismytton** [comment]
> This pull request will need to be rebased onto master once #28 has been merged.

Have rebased onto #28 and changed the base branch of this pull request for now.

**Pull request merged**
